### ISSUE TITLE
[Mobile] Token list select breaks the layout

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-wallet-monorepo#1732]
<img src="https://user-images.githubusercontent.com/381895/222728767-03941792-245d-4ccf-8e35-850d0e0318f6.PNG" width="300" />

The page gets a horizontal scroll.

**Comment by usame-algan** [comment]
We could collapse it like this:
![Image](https://user-images.githubusercontent.com/5880855/223468397-51de6414-cb85-492a-a91e-8998c9f6a9ba.png)

Wdyt @liliiaorlenko ?

**Comment by liliiaorlenko** [comment]
this version would be better for me:
https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=1004%3A50825&t=ZeRU3jFtYFaBJ4x1-1
