### ISSUE TITLE
[TX flow] tx overview confirm block (send token)

### ISSUE THREAD

**Issue by johannesmoormann** [safe-global/safe-wallet-monorepo#2027]
<img width="474" alt="Screenshot 2023-05-22 at 15 36 40" src="https://github.com/safe-global/safe-wallet-web/assets/93598450/2bc4dfbe-2ec7-4141-baae-f243056c28d1">

- including Redefine (just design) but as async needs to be optional -> needs further discussion 
-

**Comment by usame-algan** [comment]
I will create a separate issue for the balance change block as part of the Redefine implementation
