### ISSUE TITLE
no 'connect wallet' component

### ISSUE THREAD

**Issue by zzlune** [safe-global/safe-wallet-monorepo#2515]
## Bug description
I am experiencing errors when attempting to locally deploy a safe-wallet-web to support the BSC Testnet.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: BSC Testnet

## Steps to reproduce
 1. Run the web project locally
 2. Click the 'Connect Wallet'

## Screenshots

https://github.com/safe-global/safe-wallet-web/assets/16474758/8548c324-7d56-4cb2-abbb-7e0470fd53d4

**Comment by katspaugh** [comment]
Try setting the NEXT_PUBLIC_INFURA_TOKEN environment variable in your .env file.

**Comment by katspaugh** [comment]
So what was it?
