### ISSUE TITLE
Continue button is not disabled for the high risk errors from Redefine when "I understand a risk.." checkbox is not checked

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-monorepo#2955]
## Bug description
Continue button is not disabled for the high risk errors from Redefine when "I understand a risk.." checkbox is not checked
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
1. start the tx with high risk from redefine 
2.  check sign or execute button status when "I understand a risk.." checkbox is not checked

Current result: the continue is available without checking "I understand a risk.." checkbox

## Expected result
Make sure that the continue button is disabled until the "I understand a risk..." checkbox is selected
## Screenshots
![image](https://github.com/safe-global/safe-wallet-web/assets/338622/ef314937-7c6b-40f7-84fa-d117130c3bb4)

**Comment by usame-algan** [comment]
I suggest to also add tests to cover this in the context of https://github.com/safe-global/safe-wallet-web/issues/2355
