### ISSUE TITLE
Copy safe address on mobile view doesn't work

### ISSUE THREAD

**Issue by usame-algan** [safe-global/safe-wallet-monorepo#3988]
## Bug description

Trying to copy the safe address from the sidebar when having the app open on a mobile phone doesn't do anything.

## Environment
 - Browser: Safari
 - Wallet: MetaMask
 - Chain: Any

## Steps to reproduce
 1. Open app.safe.global on mobile safari
 2. Open a Safe
 3. Open the Sidebar and press the copy button

## Expected result

The safe address should be copied and there should be some ui feedback to the user

## Obtained result

Nothin happens and nothing is copied

## Screenshots
![IMG_7209](https://github.com/user-attachments/assets/102b2e15-61c4-4df6-97f3-ec29d660484c)

**Comment by HarshS1611** [comment]
Hey, could you assign this issue to me?

**Comment by jmealy** [comment]
> Hey, could you assign this issue to me?

Thanks @HarshS1611!

**Comment by HarshS1611** [comment]
Hey @jmealy, thanks for assigning the issue. I have raised the PR #4009 . Kindly review and let me know your thoughts.


https://github.com/user-attachments/assets/f2ab20a6-5780-48a1-92d4-a788d2b31868
