### ISSUE TITLE
Avoid scrolling for long tx modals

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-monorepo#837]
## What is the feature about

Long modals hiding action buttons:

![image](https://user-images.githubusercontent.com/20442784/194271259-103c4d88-c8a5-4a70-91c3-c6895b9451ad.png)

## The list of requirements

- Make the modal fit in the screen w/o scrolling.

## Designs/sketches

tbd

## Links

- [Feedback document](https://www.notion.so/gnosis-safe/Rebranding-Feedback-d5561d3c88fc456cb15e93f867e0c971)

**Comment by katspaugh** [comment]
@TanyaEfremova @liliiaorlenko we now made the whole page scroll when the popup is too long. Is this feedback still relevant then?

https://user-images.githubusercontent.com/381895/202446318-fb97912b-d2de-4178-aa36-8d39503cc3f7.mov

**Comment by katspaugh** [comment]
@lukasschor proposes displaying source and destination address next to each other:

> really no reason to display the full length address
> Making the action buttons sticky feels more hacky.

**Comment by lukasschor** [comment]
Also think showing the ETH balance adds very little value here, but could be wrong.

**Comment by katspaugh** [comment]
Agree, it's not the Safe who is paying the gas, is it. Made a separate issue for that: https://github.com/safe-global/web-core/issues/1428

**Comment by katspaugh** [comment]
Arguably, the "from" address is also redundant, since it's just the current Safe.

**Comment by liliiaorlenko** [comment]
In future design iterations, I would like to propose a concept of not using modal windows signing/executing. 
See wireframe https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=3015%3A66466&t=kkr2WIdy0r3DBZWQ-1

The same type of drawer we gonna use at Safe Apps new main page and I would like to reused it to offload singing modals, that already growing in unmanageable scroll. 

I will work on this concept in late Jan - Feb.

**Comment by katspaugh** [comment]
Closing then.
